version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  crudexample:
    image: ${DOCKER_REGISTRY-}crudexample
    build:
      context: .
      dockerfile: CRUDExample/Dockerfile
